node ("${NODE}"){
    try {
        wrap([$class: 'AnsiColorBuildWrapper', colorMapName: 'xterm']) {
            cleanWs()
            def GIT_TARGET_DIRECTORY="${WORKSPACE}"
            def GIT_REPOSITORY="https://github.com//KU0Z/MetaPhoto-Proyect.git"
            def GIT_BRANCH="${ENV}"
            def GIT_KEY="access_jenkins"
            def GIT_CHECKOUT_PATH="MetaPhoto-IAAC/terraform/"
            stage("Checkout") {
                checkout([
                    $class: "GitSCM",
                    branches: [[name: "${GIT_BRANCH}"]],
                    extensions: [
                    [$class: "CleanBeforeCheckout"],
                    [$class: "SparseCheckoutPaths",
                    sparseCheckoutPaths:[[$class:'SparseCheckoutPath', path: "${GIT_CHECKOUT_PATH}"]]],
                    [$class: "RelativeTargetDirectory",
                    relativeTargetDir: "${GIT_TARGET_DIRECTORY}"]
                    ],
                    userRemoteConfigs: [[
                    url: "${GIT_REPOSITORY}",
                    credentialsId: "${GIT_KEY}"
                    ]]
                ])
            }
            env.TF_FOLDER = "MetaPhoto-IAAC/terraform/loadbalacers"
            env.VAR_FILE = "${ENV}.tfvars"
            env.TF_VAR_e_bucket = "${BUCKET}"
            env.TF_VAR_key = "loadbalacers/${ENV}"
            env.TF_VAR_aws_region = "${AWS_REGION}"
            sh "aws s3 cp s3://${env.TF_VAR_e_bucket}/outputs/route53/${ENV}/route53_outputs.info ${WORKSPACE}/"
            sh "aws s3 cp s3://${env.TF_VAR_e_bucket}/outputs/networking/${ENV}/subnet_outputs.info ${WORKSPACE}/"
            env.TF_VAR_vpc= sh(
                script: 'echo $(cat subnet_outputs.info| grep gestor_hz| cut -d \'=\' -f 2| tr -d \'"\')',
                returnStdout: true
            ).trim()
            env.TF_VAR_api_meta_photos_subnet_1= sh(
                script: 'echo $(cat subnet_outputs.info| grep api_meta_photos_subnet_1| cut -d \'=\' -f 2| tr -d \'"\')',
                returnStdout: true
            ).trim()
            env.TF_VAR_api_meta_photos_subnet_2= sh(
                script: 'echo $(cat subnet_outputs.info| grep api_meta_photos_subnet_2| cut -d \'=\' -f 2| tr -d \'"\')',
                returnStdout: true
            ).trim()
            env.TF_VAR_security_group= sh(
                script: 'echo $(cat subnet_outputs.info| grep security_group_load| cut -d \'=\' -f 2| tr -d \'"\')',
                returnStdout: true
            ).trim()
            env.TF_VAR_hotedZone= sh(
                script: 'echo $(cat subnet_outputs.info| grep gestor_hz| cut -d \'=\' -f 2| tr -d \'"\')',
                returnStdout: true
            ).trim()
            env.TF_VAR_app_photos_certificate= sh(
                script: 'echo $(cat route53_outputs.info| grep api_certificate_net_arn| cut -d \'=\' -f 2| tr -d \'"\')',
                returnStdout: true
            ).trim()
            sh "sed -i 's/security_group=.*/security_group=\"${env.TF_VAR_security_group}\"/' ${env.TF_FOLDER}/${env.VAR_FILE}"
            sh "sed -i 's/vpc=.*/vpc=\"${env.TF_VAR_vpc}\"/' ${env.TF_FOLDER}/${env.VAR_FILE}"
            sh "sed -i 's/public_subnet_1=.*/public_subnet_1=\"${env.TF_VAR_api_meta_photos_subnet_1}\"/' ${env.TF_FOLDER}/${env.VAR_FILE}"
            sh "sed -i 's/public_subnet_2=.*/public_subnet_2=\"${env.TF_VAR_api_meta_photos_subnet_2}\"/' ${env.TF_FOLDER}/${env.VAR_FILE}"
            sh "sed -i 's/hotedZone=.*/hotedZone=\"${env.TF_VAR_hotedZone}\"/' ${env.TF_FOLDER}/${env.VAR_FILE}"
            //sh "sed -i 's/meta_photos_certificate=.*/meta_photos_certificate=\"${env.TF_VAR_app_certificate_net_arn}\"/' ${env.TF_FOLDER}/${env.VAR_FILE}"
            sh "sed -i '\$ a photos_certificate=\"${env.TF_VAR_app_photos_certificate}\"'  ${env.TF_FOLDER}/${env.VAR_FILE}"
            sh "cat ${env.TF_FOLDER}/${env.VAR_FILE}"
            
            stage("init") {
                if (fileExists("./${env.TF_FOLDER}/.terraform/terraform.tfstate")) {
                    sh "rm -rf ./${env.TF_FOLDER}/.terraform/terraform.tfstate"
                }
                if (fileExists("./${env.TF_FOLDER}/.terraform/terraform.tfstate.backup")) {
                    sh "rm -rf ./${env.TF_FOLDER}/.terraform/terraform.tfstate.backup"
                }
                if (fileExists("./${env.TF_FOLDER}/terraform.tfstate")) {
                    sh "rm -rf ./${env.TF_FOLDER}/terraform.tfstate"
                }
                if (fileExists("./${env.TF_FOLDER}/terraform.tfstate.backup")) {
                    sh "rm -rf ./${env.TF_FOLDER}/terraform.tfstate.backup"
                }
                sh " cd ${env.TF_FOLDER} && terraform init -lock=false \
                 -backend-config='bucket=${env.TF_VAR_e_bucket}' \
                 -backend-config='key=states/${env.TF_VAR_key}/terraform.tfvars' \
                 -backend-config='region=${env.TF_VAR_aws_region}' -force-copy"

                 if (env.DESTROY == "1") {
                    stage "DESTROY"
                    sh "cd ./${env.TF_FOLDER} && set +e; terraform get"
                    sh "cd ./${env.TF_FOLDER} && set +e; terraform destroy -auto-approve -var-file='${env.VAR_FILE}'"
                }
                else {
                    stage 'PLAN'
                    sh "cd ./${env.TF_FOLDER} && set +e; terraform get"
                    sh "cd ./${env.TF_FOLDER} && set +e; terraform plan -out=plan.out -var-file='${env.VAR_FILE}'"

                    if (env.APPLY=="yes") {
                        stage 'APPLY'
                        sh "cd ./${env.TF_FOLDER} && set +e; terraform apply plan.out"
                    }
                }
            }
            if (env.APPLY=="yes") {
                sh "aws s3 cp s3://${env.TF_VAR_e_bucket}/states/${env.TF_VAR_key}/terraform.tfvars ${WORKSPACE}/terraform.tfvars"
                sh "echo env.TF_VAR_api_meta_photos_tg=\$(jq \'.outputs.api_meta_photos_tg | .value\' ${WORKSPACE}/terraform.tfvars) >> ${WORKSPACE}/loadbalacers_outputs.info"
                sh "aws s3 cp ${WORKSPACE}/loadbalacers_outputs.info s3://${env.TF_VAR_e_bucket}/outputs/${env.TF_VAR_key}/loadbalacers_outputs.info"
                
            }
        }
    }
    catch (error) {
        currentBuild.result="FAILURE"
        throw error
    }
    finally {
    }
}